# Generated by Django 3.2.9 on 2021-11-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=10)),
                ('upc', models.IntegerField()),
                ('barcode', models.IntegerField(max_length=14)),
                ('outer_barcode', models.IntegerField(max_length=14)),
                ('upp', models.IntegerField()),
                ('cpp', models.IntegerField()),
                ('cs_per_layer', models.IntegerField()),
                ('layer', models.IntegerField()),
            ],
        ),
    ]
