# Generated by Django 3.2.9 on 2021-12-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('channel', models.CharField(max_length=100)),
                ('sku_type', models.CharField(max_length=100)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku.product')),
            ],
        ),
    ]
